// BUTTON STYLES
export const BUTTON_PRIMARY = 'BUTTON_PRIMARY'
export const BUTTON_SECONDARY = 'BUTTON_SECONDARY'
export const BUTTON_LINK = 'BUTTON_LINK'
export const BUTTON_SUCCESS = 'BUTTON_SUCCESS'
export const BUTTON_DANGER = 'BUTTON_DANGER'